spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/vaultguard}
spring.datasource.username=${DATABASE_USERNAME:vaultguard}
spring.datasource.password=${DATABASE_PASSWORD:vaultguard}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
